# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maria Rydzy
email:
  pl: "moje_imie@moje_nazwisko.pl"
  en: "my_name@my_family_name.pl"

description: > # this means to ignore newlines until "baseurl:"
pl: Prywatna strona Marii Rydzy. Społeczeństwo, technologia, edukacja, śniadania w Krakowie i trochę rzeczy, o których jeszcze nie wiem że napiszę.
en: Private website of Maria Rydzy. Society, technology, education, breakfasts in Krakow and some things that I don't know yet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
languages: ["en", "pl"]
default_lang: "pl"
include: ['_pages']
exclude_from_localization: ["assets", "css", "_sass", "_plugins"]
About:
  pl: O mnie
  en: About